feat: store history oss evaluation score
originjs/oss-evaluation-service pull request #664
Opened 2024-08-15 08:34 UTC by TRebirthC

store history oss evaluation score to table oss_evaluate_summary_history on the first day of each month

2024-08-16 04:00 UTC, Jiannan-dev requested changes
这个定时器只是保证了数据写入history吧，当前每个月自动重新计算分数的逻辑有保证吗？

2024-08-16 04:00 UTC, Jiannan-dev commented on packages/integration/controllers/evaluate.js
> +  await sequelize.query(`INSERT IGNORE INTO
这个SQL不是insert吗？ 为什么调用的是sequelize.query？尽量保持语义统一

2024-08-16 04:17 UTC, TRebirthC commented
> 这个定时器只是保证了数据写入history吧，当前每个月自动重新计算分数的逻辑有保证吗？

重新计算分数的定时器提交在了 [commit] [feat: update evaluate score on the first of each month](https://github.com/originjs/oss-evaluation-service/commit/6db855966375941b45b68102bc5b831ce9360c36) 和 [commit] [fix: syntax problems](https://github.com/originjs/oss-evaluation-service/commit/003e6626f8225bfd03637a1de989a8a268dec945)

2024-08-16 07:55 UTC, Jiannan-dev requested changes
将计算score和存入历史表的逻辑定时器合二为一防止历史表存入错误的数据

2024-08-16 07:57 UTC, TRebirthC commented on packages/integration/controllers/evaluate.js
> +  await sequelize.query(`INSERT IGNORE INTO
这里需要使用INSERT IGNORE语句，不使用sequelize.query的替代方法是findOrCreate。但findOrCreate不支持联合唯一键，无法处理对应表的INSERT IGNORE命令，故采用sequelize.query。

2024-08-16 08:03 UTC, Jiannan-dev requested changes
如果真的存在重复计算多次的情况应该使用新的覆盖旧的而不是直接忽略
使用insert or update 替代 insert ignore
``` sql
 INSERT INTO target_table (id, name, email)
    SELECT id, name, email FROM source_table
    ON DUPLICATE KEY UPDATE target_table.name = source_table.name, target_table.email = source_table.email;
```

2024-08-16 08:28 UTC, TRebirthC commented
> 将计算score和存入历史表的逻辑定时器合二为一防止历史表存入错误的数据

在 [Commit] [refactor: combine the timers that calculates the score and stores the history table into one](https://github.com/originjs/oss-evaluation-service/pull/664/commits/eb9bb91aafa4cafe0517579868c8145a8be08b96) 中进行了修改

2024-08-16 08:29 UTC, TRebirthC commented
> 如果真的存在重复计算多次的情况应该使用新的覆盖旧的而不是直接忽略 使用insert or update 替代 insert ignore
> 
> ```sql
>  INSERT INTO target_table (id, name, email)
>     SELECT id, name, email FROM source_table
>     ON DUPLICATE KEY UPDATE target_table.name = source_table.name, target_table.email = source_table.email;
> ```

在 [commit] [fix: replace insert ignore with insert or update](https://github.com/originjs/oss-evaluation-service/pull/664/commits/d45f7da9648bbfa4174242bbe62ee204dc72ad04) 中进行了修改

2024-08-19 09:24 UTC, Jiannan-dev requested changes

2024-08-19 09:24 UTC, Jiannan-dev commented on packages/integration/controllers/evaluate.js
> +  date = CURDATE(), function_score = VALUES(function_score), quality_score = VALUES(quality_score),
移除 date = curdate()， 唯一键中包含了date字段，所以不存在冲突的情况

2024-08-19 09:28 UTC, TRebirthC commented on packages/integration/controllers/evaluate.js
> +  date = CURDATE(), function_score = VALUES(function_score), quality_score = VALUES(quality_score),
在 [commit] [fix: remove the update of date](https://github.com/originjs/oss-evaluation-service/pull/664/commits/7f4c9b4858a5780481fe43dd522898496a2759fb) 中进行了修改

2024-08-19 09:29 UTC, Jiannan-dev approved these changes

2024-08-19 09:29 UTC, merged