fix: fix design issues with increases and total values calculation logic
originjs/oss-evaluation-service pull request #681
Opened 2024-08-28 02:44 UTC by TRebirthC

1. 删除了生态评分、质量评分的年度数据计算逻辑（该类数据意义不大）
2. 修改了star、contributor的年度数据计算逻辑（增长量：今年1月-去年1月，总量：今年1月），且仅在1月份执行（减轻数据表的长度压力）
3. 对使用REST API时出现的异常情况进行了处理（若请求失败，重新请求，最多三次）
4. 集成githubHistory数据时，跳过已存在的记录（若stars或contributors为空则不跳过）
5. 存取数据时统一改为系统时间而不是数据库时间
6. 将evaluate-summary-history中原生SQL改为结构化查询

2024-08-28 09:24 UTC, Jiannan-dev requested changes

2024-08-28 09:24 UTC, Jiannan-dev commented on packages/integration/util/fetchWithRetries.js
> +export async function fetchWithRetries(url, options = {}, attempts = 3) {
1、重试加入等待时间，例如第一次重试失败之后等待5s进入第二次重试
2、使用for 替换递归，在这个场景下递归复杂化了问题

2024-08-28 09:24 UTC, Jiannan-dev commented on packages/integration/controllers/projectHistory.js
> +    if (existRecordList) {
减少if的嵌套，比较常用的手法是const existRecordList = (await getExistRecord())??[];   
这样可以省略if(existRecordList)的判断

2024-08-28 09:24 UTC, Jiannan-dev commented on packages/integration/controllers/projectHistory.js
> +      'DATE(Date) = CURDATE() AND contributors IS NOT NULL and stars IS NOT NULL',
为什么使用原生SQL而不是结构化的查询？
``` js
where: {
        contributors: {
            [Op.ne]: null // contributors 不为 NULL
        },
        stars: {
            [Op.ne]: null // stars 不为 NULL
        }
    }
```

2024-08-28 11:19 UTC, TRebirthC commented on packages/integration/controllers/projectHistory.js
> +      'DATE(Date) = CURDATE() AND contributors IS NOT NULL and stars IS NOT NULL',
已修改成结构化的查询。

关于日期匹配问题：
1. 传入new Date()和dayjs类型时，执行SQL语句时会按照时刻进行匹配，比如‘date’ = ‘2024-08-28 11:12:20’。而表中存储的Date类型仅到日期，使用这种方式无法匹配到数据。
2. 使用CURDATE()命令，该命令仅返回到日期，可以正常匹配。

2024-08-28 11:19 UTC, TRebirthC commented on packages/integration/controllers/projectHistory.js
> +    if (existRecordList) {
已完成修改

2024-08-28 11:19 UTC, TRebirthC commented on packages/integration/util/fetchWithRetries.js
> +export async function fetchWithRetries(url, options = {}, attempts = 3) {
已按照意见进行修改

2024-08-29 01:59 UTC, TRebirthC commented on packages/integration/controllers/projectHistory.js
> +      'DATE(Date) = CURDATE() AND contributors IS NOT NULL and stars IS NOT NULL',
1. 已将相关model的date字段的类型改为DATEONLY，解决了日期不匹配的问题，目前使用new Date()来获取系统当前日期
2. 趋势榜单二所有相关存取时间统一为系统操作时间而非数据库时间
3. evaluate-summary-history中原生SQL查询改为结构化查询

2024-08-29 06:07 UTC, merged