feat: new trend ranking interface design
originjs/oss-evaluation-service pull request #690
Opened 2024-09-09 01:58 UTC by TRebirthC

# 趋势榜单二接口设计

## 入参

- dataType (string): ‘1’对应star，‘2’对应contributor，‘3’对应生态评分，‘4’对应质量评分
- dateType (string): ‘1’对应年度数据，‘2’对应月度数据，其他不返回
- rankType (string): ‘1’对应增长量，其他对应总量
- language (string): 输入编程语言的全称，目前具有116种，建议前端仅列出常见的选项，参考选项——‘JavaScript’，‘TypeScript’，‘Python’，‘Java’，‘Go’，‘C’，‘C++’，‘Rust’，‘Shell’，‘C#’，‘HTML’，‘Swift’，‘Ruby’（这里按项目数量降序排序，其他语言都少于100个项目，另外，‘All’表示所有语言）
- pageNo (string): 表示第几页的榜单
- pageSize (string): 表示每页显示多少项目

## 返回

- 当前阶段排名
- 上一阶段排名
- 当前阶段增长量
- 当前阶段总量
- 项目名
- 项目图标
- 项目网址
- 项目描述

2024-09-09 02:49 UTC, Jiannan-dev requested changes

2024-09-09 02:49 UTC, Jiannan-dev commented on packages/api-server/src/services/TrendService.ts
> +  if (dateType == DATE_TYPE.MONTH) {
else if?

2024-09-09 02:49 UTC, Jiannan-dev commented on packages/api-server/src/services/TrendService.ts
> +  const language = type.language === 'All' ? null : type.language;
对于language的筛选最好是先查询出projectId，在后续的查询中用in限制projectId的范围，因为后续还会增加其他的筛选条件
例如
``` js
// 语言筛选
const projectIds = githubProject.findAll({
        attributes: ['id'],
        where: {
          language: language,
        },
      });


```

2024-09-09 02:49 UTC, Jiannan-dev commented on packages/api-server/src/services/TrendService.ts
> +  const pageSize = page.pageSize;
排名的数据是否可以使用开窗函数直接获取，而不是在js中计算？这样也可以免去假分页的逻辑

2024-09-09 02:58 UTC, Jiannan-dev commented on packages/api-server/src/services/TrendService.ts
> +  const pageSize = page.pageSize;
mysql 的 row_number()函数可以获取当前的排名

2024-09-09 06:34 UTC, TRebirthC commented on packages/api-server/src/services/TrendService.ts
> +  if (dateType == DATE_TYPE.MONTH) {
已修改

2024-09-09 08:52 UTC, TRebirthC commented on packages/api-server/src/services/TrendService.ts
> +  const language = type.language === 'All' ? null : type.language;
目前的代码符合该思路。修改了不进行筛选时的查询逻辑——不再使用in限制projectId的范围（原先的逻辑是不筛选时提供全部的projectId，再用in限制范围）。

2024-09-09 09:27 UTC, TRebirthC commented on packages/api-server/src/services/TrendService.ts
> +  const pageSize = page.pageSize;
修改内容如下：

- 获取当前阶段排名时使用开窗函数直接获取，并使用row_number()获取排名；
- 获取上一阶段排名时获取符合筛选条件的所有数据，同时使用row_number()获取排名（仅返回projectId和rank列，减少内存占用）；

注意：
sequelize结构化查询时row_number()的执行是在查询结果之后，难以实现查询过程中生成rank再进行where过滤的操作。因此，选择先获取上一阶段的所有排名数据，再在js进行过滤。此过程中仅需要projectId和rank，相比之前极大减少了内存占用。

经过实测，修改后的代码查询所有语言时的总体时间开销降低了很多（查20个项目>1000ms→<500ms）。

2024-09-10 02:37 UTC, Jiannan-dev requested changes

2024-09-10 02:37 UTC, Jiannan-dev commented on packages/api-server/src/services/TrendService.ts
> +    attributes: [
直接使用原生的SQL，示例搜索 QUERY_SQL

2024-09-10 02:37 UTC, Jiannan-dev commented on packages/api-server/src/services/TrendService.ts
> +    attributes: [
``` sql
select history.*, row_number() over (order by increased_value desc) as num
from trend_history history
         join github_projects projects
              on history.project_id = projects.id
where history.data_type = 1
  and date_type = 2
  and language = 'Java'
  and date = '2024-09-01'
  and project_id > 1000
  and project_id < 1000000
order by increased_value desc
limit 50,50;
```

2024-09-10 02:39 UTC, Jiannan-dev commented on packages/api-server/src/services/TrendService.ts
> +    attributes: [
``` sql
select *
from (select history.*, row_number() over (order by increased_value desc) as num
      from trend_history history
               join github_projects projects
                    on history.project_id = projects.id
      where history.data_type = 1
        and date_type = 2
        and language = 'Java'
        and date = '2024-08-01'
        and project_id > 1000
        and project_id < 1000000
      order by increased_value desc) tmp
where project_id in (
    205417
    )
```

2024-09-10 06:08 UTC, TRebirthC commented on packages/api-server/src/services/TrendService.ts
> +    attributes: [
已修改为使用原生SQL查询

2024-09-10 06:36 UTC, Jiannan-dev requested changes

2024-09-10 06:36 UTC, Jiannan-dev commented on packages/api-server/src/controllers/Trend.ts
> +  @Get('new/{dataType}')
这个路由中的new是什么意思？

2024-09-10 06:36 UTC, Jiannan-dev commented on packages/api-server/src/services/TrendService.ts
> +    rawOrderCriteria = `increased_value desc, total_value desc`;
为什么这里会有两种查询条件同时存在？我理解要么都用结构化查询，要么都用原生查询

2024-09-10 06:36 UTC, Jiannan-dev commented on packages/api-server/src/services/TrendService.ts
> +    const QUERY_LAST_RANK =
这两个QUERY_LAST_RANK 大部分内容一致，减少if 条件中的语句，例如
``` js
let inProjectsSQL = githubProjectIds?.length? 'and project_id in (:githubProjectIds) : "" '
const QUERY_LAST_RNAK = `
select project_id as projectId, lastRank
      from (select history.*, row_number() over () as lastRank
      from trend_history history
      where history.data_type = :dataType
        and date_type = :dateType
        and date = :selectedDate
       ${inProjectsSQL}
      order by ...
`;

```

2024-09-10 06:36 UTC, Jiannan-dev commented on packages/api-server/src/services/TrendService.ts
> +      order by ` +
使用 ``来声明字符串，可以直接在字符串中使用变量，无须+
``` js
`... ${rawOrderCriteria}`
```

2024-09-10 06:40 UTC, TRebirthC commented on packages/api-server/src/controllers/Trend.ts
> +  @Get('new/{dataType}')
跟老的趋势榜单做区分。不加这个new在调用Swagger UI接口时，点击新的趋势榜单接口会同时弹开老的接口。

2024-09-10 06:41 UTC, TRebirthC commented on packages/api-server/src/services/TrendService.ts
> +      order by ` +
已修改

2024-09-10 07:46 UTC, TRebirthC commented on packages/api-server/src/services/TrendService.ts
> +    const QUERY_LAST_RANK =
已将两个QUERY_LAST_RANK合并

2024-09-10 07:47 UTC, TRebirthC commented on packages/api-server/src/services/TrendService.ts
> +    rawOrderCriteria = `increased_value desc, total_value desc`;
已统一使用原生查询

2024-09-10 07:54 UTC, merged